
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu20482156n
 */
public class Cover extends javax.swing.JDialog {

    /**
     * Creates new form Cover
     */
    private boolean modeSelected;

    public static boolean personalizedMode;

    private JFrame parentFrame;

    public void setParentFrame(JFrame parentFrame) {
        this.parentFrame = parentFrame;
    }

    public Cover(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //centra el JPanel

        modeSelected = false;
        personalizedMode = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGo = new javax.swing.JButton();
        jButtonClassic = new javax.swing.JButton();
        jButtonNoWalls = new javax.swing.JButton();
        jButtonPersonalized = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonGo.setText("Go!");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });

        jButtonClassic.setText("Snake Classic");
        jButtonClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassicActionPerformed(evt);
            }
        });

        jButtonNoWalls.setText("Snake without walls");
        jButtonNoWalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoWallsActionPerformed(evt);
            }
        });

        jButtonPersonalized.setText("Personalized");
        jButtonPersonalized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPersonalizedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonGo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPersonalized)
                            .addComponent(jButtonClassic))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(jButtonNoWalls)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButtonClassic)
                .addGap(33, 33, 33)
                .addComponent(jButtonNoWalls)
                .addGap(34, 34, 34)
                .addComponent(jButtonPersonalized)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jButtonGo)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        if (modeSelected) {
            dispose();
        }

    }//GEN-LAST:event_jButtonGoActionPerformed

    private void jButtonClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassicActionPerformed
        ConfigSingleton.getInstance().setNoWalls(false);
        modeSelected = true;

    }//GEN-LAST:event_jButtonClassicActionPerformed

    private void jButtonNoWallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoWallsActionPerformed
        ConfigSingleton.getInstance().setNoWalls(true);
        modeSelected = true;

    }//GEN-LAST:event_jButtonNoWallsActionPerformed

    private void jButtonPersonalizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPersonalizedActionPerformed
        personalizedMode = true;

        Personalized personalized = new Personalized(parentFrame, true);
        personalized.setVisible(true);
        modeSelected = true;
    }//GEN-LAST:event_jButtonPersonalizedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClassic;
    private javax.swing.JButton jButtonGo;
    private javax.swing.JButton jButtonNoWalls;
    private javax.swing.JButton jButtonPersonalized;
    // End of variables declaration//GEN-END:variables
}
