
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu20482156n
 */
public class RecordsDialog extends javax.swing.JDialog {

    private class Record {

        public int record;
        public String name;

        public Record(int record, String name) {
            this.record = record;
            this.name = name;
        }
    }

    private static final String RECORDS_FILE_NAME = "records.txt";
    private int score;
    private JLabel[] recordLabels;
    private int minRecord;
    private ArrayList<Record> listOfRecords;

    public RecordsDialog(java.awt.Frame parent, boolean modal, int score) {
        super(parent, modal);
        initComponents();

        initRecordLabels();

        minRecord = 0;
        this.score = score;

        listOfRecords = new ArrayList<Record>();

        try {
            readRecords();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

         processRecords();
    }

    private void initRecordLabels() {
        recordLabels = new JLabel[5];

        recordLabels[0] = jLabelRecord1;
        recordLabels[1] = jLabelRecord2;
        recordLabels[2] = jLabelRecord3;
        recordLabels[3] = jLabelRecord4;
        recordLabels[4] = jLabelRecord5;

    }
    
    public void processRecords() {
        jLabelCurrentScore.setText("Your score: " + score);
        if (score > minRecord) {

        } else {
            jLabelName.setVisible(false);
            jTextFieldName.setVisible(false);
        }
    }

    private void readRecords() throws IOException {
        BufferedReader input = null;

        try {
            input = new BufferedReader(new FileReader(RECORDS_FILE_NAME));

            int lineCount = 0;
            String line;
            String[] lineRecord = null;

            while ((line = input.readLine()) != null && (lineCount < 5)) {

                lineRecord = line.split(",");
                recordLabels[lineCount].setText(lineRecord[0] + ": " + lineRecord[1]);
                lineCount++;

                listOfRecords.add(new Record(Integer.parseInt(lineRecord[0]), lineRecord[1]));
            }
            if (lineCount > 0 && lineCount >= 5) {
                try {
                    minRecord = Integer.parseInt(lineRecord[0]);
                } catch (NumberFormatException ex) {
                    ex.printStackTrace();
                }

            }

        } finally {
            if (input != null) {
                input.close();
            }
        }

    }

    private void saveRecords() throws IOException {
        PrintWriter output = null;
        try {
            output = new PrintWriter(new FileWriter(RECORDS_FILE_NAME));
            int lineCounter = 0;
            boolean alredyWrittenScore = false;

            for (Record record : listOfRecords) {
                if (record.record > score && !alredyWrittenScore) {

                    output.println(score + ", " + jTextFieldName.getText());
                    alredyWrittenScore = true;
                    lineCounter++;
                }
                if (lineCounter < 5) {
                    output.println(record.record + ", " + record.name);
                    lineCounter++;
                }
            }
            if (!alredyWrittenScore) {
                output.println(score + ", " + jTextFieldName.getText());
            }

        } finally {
            if (output != null) {
                output.close();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelRecord1 = new javax.swing.JLabel();
        jLabelRecord2 = new javax.swing.JLabel();
        jLabelRecord3 = new javax.swing.JLabel();
        jLabelRecord4 = new javax.swing.JLabel();
        jLabelRecord5 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelCurrentScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelRecord1.setText("jLabel1");

        jLabelRecord2.setText("jLabel2");

        jLabelRecord3.setText("jLabel3");

        jLabelRecord4.setText("jLabel4");

        jLabelRecord5.setText("jLabel5");

        jLabelName.setText("Name:");

        jTextFieldName.setText("Write your name");

        jLabelCurrentScore.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCurrentScore.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabelCurrentScore, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelCurrentScore)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord1)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord2)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord3)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord4)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (score > minRecord) {
            try {
                saveRecords();

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelCurrentScore;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRecord1;
    private javax.swing.JLabel jLabelRecord2;
    private javax.swing.JLabel jLabelRecord3;
    private javax.swing.JLabel jLabelRecord4;
    private javax.swing.JLabel jLabelRecord5;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
